// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SupplierService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SupplierService.proto</summary>
public static partial class SupplierServiceReflection {

  #region Descriptor
  /// <summary>File descriptor for SupplierService.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SupplierServiceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVTdXBwbGllclNlcnZpY2UucHJvdG8iIgogRmluZEFsbFByZWZlcnJlZFN1",
          "cHBsaWVyc1JlcXVlc3QiQQohRmluZEFsbFByZWZlcnJlZFN1cHBsaWVyc1Jl",
          "c3BvbnNlEhwKCXN1cHBsaWVycxgBIAMoCzIJLlN1cHBsaWVyIjkKHEZpbmRQ",
          "cmVmZXJyZWRTdXBwbGllclJlcXVlc3QSGQoHcHJvZHVjdBgBIAEoCzIILlBy",
          "b2R1Y3QiPAodRmluZFByZWZlcnJlZFN1cHBsaWVyUmVzcG9uc2USGwoIc3Vw",
          "cGxpZXIYASABKAsyCS5TdXBwbGllciJfCiVTZXRQcmVmZXJyZWRTdXBwbGll",
          "ckZvclByb2R1Y3RSZXF1ZXN0EhsKCHN1cHBsaWVyGAEgASgLMgkuU3VwcGxp",
          "ZXISGQoHcHJvZHVjdBgCIAEoCzIILlByb2R1Y3QiKAomU2V0UHJlZmVycmVk",
          "U3VwcGxpZXJGb3JQcm9kdWN0UmVzcG9uc2UiMwoIU3VwcGxpZXISCgoCaWQY",
          "ASABKAkSDAoEbmFtZRgCIAEoCRINCgVwaG9uZRgDIAEoCSI3CgdQcm9kdWN0",
          "EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEgoKc3VwcGxpZXJGaxgDIAEo",
          "CTLAAgoPU3VwcGxpZXJTZXJ2aWNlEmIKGWZpbmRBbGxQcmVmZXJyZWRTdXBw",
          "bGllcnMSIS5GaW5kQWxsUHJlZmVycmVkU3VwcGxpZXJzUmVxdWVzdBoiLkZp",
          "bmRBbGxQcmVmZXJyZWRTdXBwbGllcnNSZXNwb25zZRJWChVmaW5kUHJlZmVy",
          "cmVkU3VwcGxpZXISHS5GaW5kUHJlZmVycmVkU3VwcGxpZXJSZXF1ZXN0Gh4u",
          "RmluZFByZWZlcnJlZFN1cHBsaWVyUmVzcG9uc2UScQoec2V0UHJlZmVycmVk",
          "U3VwcGxpZXJGb3JQcm9kdWN0EiYuU2V0UHJlZmVycmVkU3VwcGxpZXJGb3JQ",
          "cm9kdWN0UmVxdWVzdBonLlNldFByZWZlcnJlZFN1cHBsaWVyRm9yUHJvZHVj",
          "dFJlc3BvbnNlYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::FindAllPreferredSuppliersRequest), global::FindAllPreferredSuppliersRequest.Parser, null, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FindAllPreferredSuppliersResponse), global::FindAllPreferredSuppliersResponse.Parser, new[]{ "Suppliers" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FindPreferredSupplierRequest), global::FindPreferredSupplierRequest.Parser, new[]{ "Product" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FindPreferredSupplierResponse), global::FindPreferredSupplierResponse.Parser, new[]{ "Supplier" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SetPreferredSupplierForProductRequest), global::SetPreferredSupplierForProductRequest.Parser, new[]{ "Supplier", "Product" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SetPreferredSupplierForProductResponse), global::SetPreferredSupplierForProductResponse.Parser, null, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Supplier), global::Supplier.Parser, new[]{ "Id", "Name", "Phone" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Product), global::Product.Parser, new[]{ "Id", "Name", "SupplierFk" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class FindAllPreferredSuppliersRequest : pb::IMessage<FindAllPreferredSuppliersRequest> {
  private static readonly pb::MessageParser<FindAllPreferredSuppliersRequest> _parser = new pb::MessageParser<FindAllPreferredSuppliersRequest>(() => new FindAllPreferredSuppliersRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<FindAllPreferredSuppliersRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SupplierServiceReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindAllPreferredSuppliersRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindAllPreferredSuppliersRequest(FindAllPreferredSuppliersRequest other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindAllPreferredSuppliersRequest Clone() {
    return new FindAllPreferredSuppliersRequest(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as FindAllPreferredSuppliersRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(FindAllPreferredSuppliersRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(FindAllPreferredSuppliersRequest other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  }

}

public sealed partial class FindAllPreferredSuppliersResponse : pb::IMessage<FindAllPreferredSuppliersResponse> {
  private static readonly pb::MessageParser<FindAllPreferredSuppliersResponse> _parser = new pb::MessageParser<FindAllPreferredSuppliersResponse>(() => new FindAllPreferredSuppliersResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<FindAllPreferredSuppliersResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SupplierServiceReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindAllPreferredSuppliersResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindAllPreferredSuppliersResponse(FindAllPreferredSuppliersResponse other) : this() {
    suppliers_ = other.suppliers_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindAllPreferredSuppliersResponse Clone() {
    return new FindAllPreferredSuppliersResponse(this);
  }

  /// <summary>Field number for the "suppliers" field.</summary>
  public const int SuppliersFieldNumber = 1;
  private static readonly pb::FieldCodec<global::Supplier> _repeated_suppliers_codec
      = pb::FieldCodec.ForMessage(10, global::Supplier.Parser);
  private readonly pbc::RepeatedField<global::Supplier> suppliers_ = new pbc::RepeatedField<global::Supplier>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Supplier> Suppliers {
    get { return suppliers_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as FindAllPreferredSuppliersResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(FindAllPreferredSuppliersResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!suppliers_.Equals(other.suppliers_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= suppliers_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    suppliers_.WriteTo(output, _repeated_suppliers_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += suppliers_.CalculateSize(_repeated_suppliers_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(FindAllPreferredSuppliersResponse other) {
    if (other == null) {
      return;
    }
    suppliers_.Add(other.suppliers_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          suppliers_.AddEntriesFrom(input, _repeated_suppliers_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class FindPreferredSupplierRequest : pb::IMessage<FindPreferredSupplierRequest> {
  private static readonly pb::MessageParser<FindPreferredSupplierRequest> _parser = new pb::MessageParser<FindPreferredSupplierRequest>(() => new FindPreferredSupplierRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<FindPreferredSupplierRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SupplierServiceReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindPreferredSupplierRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindPreferredSupplierRequest(FindPreferredSupplierRequest other) : this() {
    product_ = other.product_ != null ? other.product_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindPreferredSupplierRequest Clone() {
    return new FindPreferredSupplierRequest(this);
  }

  /// <summary>Field number for the "product" field.</summary>
  public const int ProductFieldNumber = 1;
  private global::Product product_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Product Product {
    get { return product_; }
    set {
      product_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as FindPreferredSupplierRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(FindPreferredSupplierRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Product, other.Product)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (product_ != null) hash ^= Product.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (product_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Product);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (product_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Product);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(FindPreferredSupplierRequest other) {
    if (other == null) {
      return;
    }
    if (other.product_ != null) {
      if (product_ == null) {
        Product = new global::Product();
      }
      Product.MergeFrom(other.Product);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (product_ == null) {
            Product = new global::Product();
          }
          input.ReadMessage(Product);
          break;
        }
      }
    }
  }

}

public sealed partial class FindPreferredSupplierResponse : pb::IMessage<FindPreferredSupplierResponse> {
  private static readonly pb::MessageParser<FindPreferredSupplierResponse> _parser = new pb::MessageParser<FindPreferredSupplierResponse>(() => new FindPreferredSupplierResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<FindPreferredSupplierResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SupplierServiceReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindPreferredSupplierResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindPreferredSupplierResponse(FindPreferredSupplierResponse other) : this() {
    supplier_ = other.supplier_ != null ? other.supplier_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FindPreferredSupplierResponse Clone() {
    return new FindPreferredSupplierResponse(this);
  }

  /// <summary>Field number for the "supplier" field.</summary>
  public const int SupplierFieldNumber = 1;
  private global::Supplier supplier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Supplier Supplier {
    get { return supplier_; }
    set {
      supplier_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as FindPreferredSupplierResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(FindPreferredSupplierResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Supplier, other.Supplier)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (supplier_ != null) hash ^= Supplier.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (supplier_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Supplier);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (supplier_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Supplier);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(FindPreferredSupplierResponse other) {
    if (other == null) {
      return;
    }
    if (other.supplier_ != null) {
      if (supplier_ == null) {
        Supplier = new global::Supplier();
      }
      Supplier.MergeFrom(other.Supplier);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (supplier_ == null) {
            Supplier = new global::Supplier();
          }
          input.ReadMessage(Supplier);
          break;
        }
      }
    }
  }

}

public sealed partial class SetPreferredSupplierForProductRequest : pb::IMessage<SetPreferredSupplierForProductRequest> {
  private static readonly pb::MessageParser<SetPreferredSupplierForProductRequest> _parser = new pb::MessageParser<SetPreferredSupplierForProductRequest>(() => new SetPreferredSupplierForProductRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SetPreferredSupplierForProductRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SupplierServiceReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SetPreferredSupplierForProductRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SetPreferredSupplierForProductRequest(SetPreferredSupplierForProductRequest other) : this() {
    supplier_ = other.supplier_ != null ? other.supplier_.Clone() : null;
    product_ = other.product_ != null ? other.product_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SetPreferredSupplierForProductRequest Clone() {
    return new SetPreferredSupplierForProductRequest(this);
  }

  /// <summary>Field number for the "supplier" field.</summary>
  public const int SupplierFieldNumber = 1;
  private global::Supplier supplier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Supplier Supplier {
    get { return supplier_; }
    set {
      supplier_ = value;
    }
  }

  /// <summary>Field number for the "product" field.</summary>
  public const int ProductFieldNumber = 2;
  private global::Product product_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Product Product {
    get { return product_; }
    set {
      product_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SetPreferredSupplierForProductRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SetPreferredSupplierForProductRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Supplier, other.Supplier)) return false;
    if (!object.Equals(Product, other.Product)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (supplier_ != null) hash ^= Supplier.GetHashCode();
    if (product_ != null) hash ^= Product.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (supplier_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(Supplier);
    }
    if (product_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Product);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (supplier_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Supplier);
    }
    if (product_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Product);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SetPreferredSupplierForProductRequest other) {
    if (other == null) {
      return;
    }
    if (other.supplier_ != null) {
      if (supplier_ == null) {
        Supplier = new global::Supplier();
      }
      Supplier.MergeFrom(other.Supplier);
    }
    if (other.product_ != null) {
      if (product_ == null) {
        Product = new global::Product();
      }
      Product.MergeFrom(other.Product);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (supplier_ == null) {
            Supplier = new global::Supplier();
          }
          input.ReadMessage(Supplier);
          break;
        }
        case 18: {
          if (product_ == null) {
            Product = new global::Product();
          }
          input.ReadMessage(Product);
          break;
        }
      }
    }
  }

}

public sealed partial class SetPreferredSupplierForProductResponse : pb::IMessage<SetPreferredSupplierForProductResponse> {
  private static readonly pb::MessageParser<SetPreferredSupplierForProductResponse> _parser = new pb::MessageParser<SetPreferredSupplierForProductResponse>(() => new SetPreferredSupplierForProductResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SetPreferredSupplierForProductResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SupplierServiceReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SetPreferredSupplierForProductResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SetPreferredSupplierForProductResponse(SetPreferredSupplierForProductResponse other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SetPreferredSupplierForProductResponse Clone() {
    return new SetPreferredSupplierForProductResponse(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SetPreferredSupplierForProductResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SetPreferredSupplierForProductResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SetPreferredSupplierForProductResponse other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  }

}

public sealed partial class Supplier : pb::IMessage<Supplier> {
  private static readonly pb::MessageParser<Supplier> _parser = new pb::MessageParser<Supplier>(() => new Supplier());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Supplier> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SupplierServiceReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Supplier() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Supplier(Supplier other) : this() {
    id_ = other.id_;
    name_ = other.name_;
    phone_ = other.phone_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Supplier Clone() {
    return new Supplier(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "phone" field.</summary>
  public const int PhoneFieldNumber = 3;
  private string phone_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Phone {
    get { return phone_; }
    set {
      phone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Supplier);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Supplier other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Name != other.Name) return false;
    if (Phone != other.Phone) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Phone.Length != 0) hash ^= Phone.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (Phone.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Phone);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Phone.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Phone);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Supplier other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Phone.Length != 0) {
      Phone = other.Phone;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 26: {
          Phone = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class Product : pb::IMessage<Product> {
  private static readonly pb::MessageParser<Product> _parser = new pb::MessageParser<Product>(() => new Product());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Product> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SupplierServiceReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Product() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Product(Product other) : this() {
    id_ = other.id_;
    name_ = other.name_;
    supplierFk_ = other.supplierFk_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Product Clone() {
    return new Product(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 2;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "supplierFk" field.</summary>
  public const int SupplierFkFieldNumber = 3;
  private string supplierFk_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string SupplierFk {
    get { return supplierFk_; }
    set {
      supplierFk_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Product);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Product other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Name != other.Name) return false;
    if (SupplierFk != other.SupplierFk) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (SupplierFk.Length != 0) hash ^= SupplierFk.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Id.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Id);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Name);
    }
    if (SupplierFk.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(SupplierFk);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (SupplierFk.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SupplierFk);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Product other) {
    if (other == null) {
      return;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.SupplierFk.Length != 0) {
      SupplierFk = other.SupplierFk;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Id = input.ReadString();
          break;
        }
        case 18: {
          Name = input.ReadString();
          break;
        }
        case 26: {
          SupplierFk = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
